version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: sqli-part2
    container_name: sqli-part2-app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: sqli-part2-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sqli
      MYSQL_USER: sqli
      MYSQL_PASSWORD: sqli
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
